# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56cd01d0984710944b6b3920e5f7616dcd32dc85053f1d8c04716300ba063c20488c0009c02b41972431cb4a362ec1f5b0b90cea23865777f3a577dedffc7ce2

test:
  secret_key_base: 8ad64157d4f7dfc489bfaf92366d0db303843e38c577506ec12efdefade58bbe5c3438ab9da4fc78c57c10d5333d3cf485c5b7f347840a8da7066dbfbefceade

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
